### ISSUE TITLE
Renaming the `register_component` twig function

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/web-twig#29]
Currently the [`register_component`](https://github.com/sulu/web-twig/blob/d3892b29cde9a2a456c0dfbf1e2d29290d7a4a85/src/ComponentExtension.php#L69-L97) twig function is a little bit misleading and get confused with the [webJS web.registerComponent](https://github.com/sulu/web-js#initialize-webjs-and-registering-your-components-and-services) function when try to explain the concepts of web twig / web js.

It would be great to find a better name for it, the task of the function currently the following:

 - if no id is given a id is unique id is [generated](https://github.com/sulu/web-twig/blob/d3892b29cde9a2a456c0dfbf1e2d29290d7a4a85/src/ComponentExtension.php#L77-L81)
 - in all cases the component is [remembered](https://github.com/sulu/web-twig/blob/d3892b29cde9a2a456c0dfbf1e2d29290d7a4a85/src/ComponentExtension.php#L88-L94) to later get outputted over the `get_components` function
 - the id is [returned](https://github.com/sulu/web-twig/blob/d3892b29cde9a2a456c0dfbf1e2d29290d7a4a85/src/ComponentExtension.php#L96) by the twig function so it can be set on the dom element

At current state I'm thinking about `remember_component` as this best described what in all cases happens. I was also thinking about `create_component` but it does just create an id (and not in all cases), actually create the component instance and starting it is handled by the JS. Was also thinking about just using `component` when thinking about the `asset` twig function. When changing it for backward compatibility the old function name will still be available but marked as deprecated.

Would be great to get here some feedback what you think about `remember_component` or maybe somebody have another idea.

**Comment by thomasduenser** [comment]
From your suggestions I like `remember_component` the most. Another idea would be `js_component` - this makes clear that it has something to do with a JS component.

**Comment by alexander-schranz** [comment]
@thomasduenser Thank you for your feedback. Yeah `js_component` would be a better fit then `component`. I think then I would maybe rename all function to add the `js` prefix maybe also the Extension to `JsComponentExtension`, the problem I see with `component` or `js_component` is that it does not really tell something what this function is for or what it does.

**Comment by Quehnie** [comment]
mh... like the ideas, maybe a `use_component` is the thing we are looking for...

**Comment by alexander-schranz** [comment]
@Quehnie `use_component` sounds also not so bad 🤔

**Comment by nnatter** [comment]
`remember_component` sounds a bit confusing to me, not sure what I would expect to happen when calling such a function. What do you think about `prepare_component` or `initialize_component`?

**Comment by mfehr94** [comment]
I also think that `remember_component` sounds a bit confusing. My first thought was `find_or_create_component`, but I think this would be to long. So I would stick with `prepare_component `or `initialize_component`.

**Comment by alexander-schranz** [comment]
@nnatter `initialize_component` would conflict also with the webjs initialize method so I would avoid that.

@mfehr94 thank you for your feeback `find_or_create` I think isn't anything matching because it doesn't search for something or create something. 

About `prepare_component` I need to think about a little bit because for me prepare does tell also zero about what really happens. Why you think remember is confusing? For me it currently does represent it the best what really happens in that function remember it that it can be letter get it with the `get_components` function, maybe we should then rename it to `get_remember_components` but not sure about that.

**Comment by wachterjohannes** [comment]
@alexander-schranz i would go with `initialize_component` at the end this function calls the JS method - so no conflict for me

**Comment by alexander-schranz** [comment]
The current problem is that its really confusing having the same name for something in twig and js as the js and twig are doing something complete different and renaming it from register_component to initialize_component would end into the same problem again when try to explain the concepts.

**Comment by thomasduenser** [comment]
I think we should go with `prepare_component`, as it prepares (and collects) the component instances for the usage in JS. `remember_component` is also fine for me.

**Comment by alexander-schranz** [comment]
At current state I think `prepare_component` would be the best match. In this case I think it would also make sense to rename the `call_service` function to `prepare_service_call`:

So the following would change:

`register_component` -> `prepare_component`
`call_service` -> `prepare_service_call`

What do you think about this change?

**Comment by alexander-schranz** [comment]
> I think we should go with prepare_component, as it prepares (and collects) the component instances for the usage in JS. remember_component is also fine for me.

@thomasduenser reading your comment `collect_component` / `collect_service` would have been an alternative 🤔

**Comment by thomasduenser** [comment]
@alexander-schranz That sounds very good! I would use `collect_component` and `collect_service`.
