### ISSUE TITLE
Allow srcset without <picture> element

### ISSUE THREAD

**Issue by sanderquirynen** [sulu/web-twig#33]
The [docs](https://github.com/sulu/web-twig/blob/master/docs/image.md#2-complex-image-tag) state that there's a way to get an `<img>` without a surrounding `<picture>` element. But when I try this (using the example code) I always get a surrounding `<picture>` element.

This is something you don't always want for several reasons:
- There's no way to pass custom css classes to the picture-element
- This is not the intended way for a picture-element to be used (a picture-element is meant to be used when serving **different images**, when serving **different sizes** of the same image an `<img>` element is usually the way to go)

**Possible solutions:**
Give extra options to either allow the `<picture>` to be intentionally disabled (allows for backwards compatibility). 
And possibly an extra option to add extra css-classes to the `<picture>` element itself (`margin` for example acts differently when being set on the `<picture>` or the `<img>` element inside it).

**Comment by alexander-schranz** [comment]
@sanderquirynen I'm sure that this still works as there are still tests which are testing this cases: https://github.com/sulu/web-twig/blob/1333fd36721b4ea923d85ebcdd4f2efae81da376/tests/Unit/ImageExtensionTest.php#L92-L95.

Please provide your ImageExtension configuration and how you are calling the extension.

I think what the problem is in your case is that you activated `webp` support in your ImageExtension and then its not longer a `single-source` for an image as then the there will be atleast for example 1 source with the webp and fallback to the png/jpg.

**Comment by sanderquirynen** [comment]
You are completely right. It's the webp support that is causing this.

**Comment by alexander-schranz** [comment]
@sanderquirynen webp requires to have a picture tag, else it can not provide the webp url for the modern browsers. I could think about we could implement something to disable it for a single call if that would help you in this case.

And please when creating this type of issues provide a reproduceable, telling it doesn't work and it should be another way just sounds very rude for me. I know that maybe it wasn't your intention to be rude but just want to tell you how the issue did sound for me.

**Comment by sanderquirynen** [comment]
> @sanderquirynen webp requires to have a picture tag, else it can not provide the webp url for the modern browsers and a fallback url for older browsers. I could think about we could implement something to disable it for a single call if that would help you in this case.
> 
> And please when creating this type of issues provide a reproduceable, telling it doesn't work and it should be another way just sounds very rude for me. I know that maybe it wasn't your intention to be rude but just want to tell you how the issue did sound for me.

Sorry, this was indeed not my intention. I thought the snippet in the docs was a reproduceable, because in my cause it rendered different HTML than in the docs. But this was due to the enabling of webp support as you said.
