### ISSUE TITLE
Incompatible with Symfony 7.1

### ISSUE THREAD

**Issue by RobertMe** [sulu/web-twig#49]
Hi,

When trying to update to Sulu 2.6.4 and Symfony 7.1 I'm running into a rather awkward situation. When just updating `sulu/sulu symfony/*` composer prevents the update. This is due to "sulu/web-twig v2.5.6 conflicts with symfony/property-access v7.1.1.". Additional "fun fact" is that this conflict has only be declared in version 2.5.5+ of this package (by #45), meaning that a plain `composer update` (or `composer update sulu/* symfony/*`) will happily _downgrade_ this package to 2.5.4 which doesn't have this conflict defined yet. But assuming that the conflict was declared due to some incompatibility it is my believe that with a downgraded version of this package that incompatibility will still be present (+ downgrading obviously means that the bugfixes of later versions of this package are not applied anymore).

**Comment by pounard** [comment]
I recently upgrade a project to sulu 2.6.4 and experience this problem as well. More importantly, it crashes when using twig 3.12

**Comment by alexander-schranz** [comment]
feel free to give https://github.com/sulu/web-twig/pull/50 a try and let us know if that branch works for you.
